### PR TITLE
Major refactor

### PR DESCRIPTION
**Pull request by cotejp**
Hi Evan,

As discussed previously, I decided to take a stab at re-architecting the library so it would support various board models. I also took this opportunity to fix a few bugs and add unsupported features such as: function chainability, PhidgetLED board, connection by label, new events, full api documentation, adjustable inter-report period, etc.

As forecasted, these changes broke backwards-compatibility. But as I said in my previous message, I believe this is the only way to go forward.

Do you think you can pull this in and perhaps give me access to npm too ? My username on GitHub is cotejp and my username on npm is jpcote.

### CODE REVIEW

**Comment by evantahler** [comment]
Wow, that's a lot of changes!  

I'll take some time to review this in a few days, but I'm sure that if it works, it's OK!

One general note: I fee that the /docs section doesn't belong here, and that includes the grunt tooling as well.  It ads almost 3x the number of files and assets to the project.  We don't want to have people downloading all that from NPM, and for a project this small, I really don't think that it is necessary... a readme should be enough.

**Comment by cotejp** [comment]
Yes, it's a lot of changes. At first, I was trying to separate commits into smaller chunks but I was changing so much stuff around that it became difficult to break it down into smaller pieces.

Regarding the docs and grunt stuff, you can definitely leave them out of npm. However, that does not necessarily mean to leave them out of GitHub. Since the docs are generated from source with grunt, its quite convenient to have them both in the same GitHub project (as a dev-dependency). They could just be filtered out with a .npmignore file. Or, event better, we could create a 'npm' directory that contains only what should go into the final npm.

Cheers! :-)

**Comment by evantahler** [comment]
@cotejp I've added you as a collaborator on this repo and on NPM!  

While I have some "philosophical" differences with some of your work (docs checked in, formal Object property definitions, etc), it looks good, and it looks like it works!   If you have the time/desire to maintain this project, then by all means, please go ahead and do so!

My only real suggestion to aid in the usability of the project would be extract some of the more important information into the readme.  For example, cloning the project and then digging all the way down into `node-phidgets/docs/classes/PhidgetInterfaceKit.html#event_sensor` to find the list of events that might be emitted seems cumbersome, especially when convention it do do the opposite.  Here are some examples:
- https://github.com/request/request
- https://github.com/primus/primus

I'm curious, what IDE do you use to help you code?  I'm guessing you had some help.

**Comment by evantahler** [comment]
Oh, and I'll let you push to NPM when you are ready!

**Comment by cotejp** [comment]
Excellent, thanks for your trust!

Per your suggestion, I'll add the events to the readme (that's a complete oversight on my part). When I get a little time, I'll publish to npm (probably on Friday). 

Regarding your question, I use WebStorm with a bunch of plugins (jshint, grunt, etc.). As far as I'm concerned it's one of the best IDEs out there (and since I'm a college lecturer, it's free!).

When I have a little more time, I'd be curious to hear about those philosophical differences... I'm still fairly new to the JavaScript ecosystem so I may not understand all its subtleties.

**Comment by evantahler** [comment]
good luck! 

If you want to "chat" I usually hang out here https://gitter.im/evantahler/actionhero, which is the chat for the actionhero project, the main open source thing I work on these days.

The philosophical note is mainly about "lean-ness".    The node package ecosystem tries to keep packages as small and single-purpose as possible (UNIX-philosophy), and a lot of the metaphors come from that.  For example, our phidget package is small and concince (and does one thing well).  That means that all of our documentation and arguments *should* fit on a single MAN page (or README in the modern parlance).  This also means that since the package is so small, we probably don't need so many code-comments and "formal" property definitions.  Feel free to just append properties onto an object whilly-nilly :D  As long at the API to the package is sound, the internals don't have to be so rigid. 

Like I said before those, these are "philosophy" points (and my personal opinions), and not dogma.   Working code, which you have here, is far more valuable!

**Pull request merged**
