### PR TITLE
Upgraded the library to include support for the PhidgetBridge module

### PR DESCRIPTION
**Pull request by cotejp**
Also, the creation and upload of the API documentation to GitHub pages is now automatic.

### CODE REVIEW

**Comment by evantahler** [comment]
neat!
Glad to see that you are still working on this!

**Comment by cotejp** [comment]
I just happened to need it for a talk I'm giving next Tuesday. By the way, I learned this week that Phidgets Inc. is working on their own JavaScript API which will probably be released somewhere next year.

**Comment by cotejp** [comment]
I just realized that the tags and releases are not carried over when I merge a pull request. For instance, in /evantahler/nodePhidgets there is only a release for v0.4.0. Should I manually create one for v0.5.1-alpha.1 ?

**Comment by evantahler** [comment]
yep, absolutely!

**Pull request merged**
